before_script: 
  - composer install

stages:
  - test

php5.6:
  stage: test
  image: php:5.6
  script:
    - vendor/bin/phpunit

php7.0:
  stage: test
  image: php:7.0
  script:
    - vendor/bin/phpunit

php7.1:
  stage: test
  image: php:7.1
  script:
    - vendor/bin/phpunit
